kind = "DojoContract"
class_hash = "0x389b5a4f2bc67b9ec31b34134f2ec074c2d83d851478b597b1f4f1d18ebfdb9"
original_class_hash = "0x389b5a4f2bc67b9ec31b34134f2ec074c2d83d851478b597b1f4f1d18ebfdb9"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/memory_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "memory::systems::actions::actions"
