[world]
kind = "Contract"
class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
original_class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
abi = "abis/deployments/dojo_world_world.json"
address = "0x65b00d9f1fed5bbe604b987ee1d25b51f0aaa53b81cfdcc010f46d25a7f2dd7"
transaction_hash = "0x453da3a0ac1442df79d64e9fc648e147104a1592554cfa4b62d623543d519aa"
block_number = 3
seed = "memory"
name = "dojo::world::world"

[base]
kind = "Class"
class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
original_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x269dad70ba295e4100e6ed5bfd44e8abb9a9068d6912aa91e0079b15bdc2482"
class_hash = "0x389b5a4f2bc67b9ec31b34134f2ec074c2d83d851478b597b1f4f1d18ebfdb9"
original_class_hash = "0x389b5a4f2bc67b9ec31b34134f2ec074c2d83d851478b597b1f4f1d18ebfdb9"
base_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
abi = "abis/deployments/contracts/memory_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "memory::systems::actions::actions"

[[models]]
kind = "DojoModel"
class_hash = "0x5ae35e0213832d2c3e53336e28db0b15ca811dc1a35c3be234f4b7787b7fe4e"
original_class_hash = "0x5ae35e0213832d2c3e53336e28db0b15ca811dc1a35c3be234f4b7787b7fe4e"
abi = "abis/deployments/models/memory_models_game_game.json"
name = "memory::models::game::game"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "ended"
type = "bool"
key = false

[[models.members]]
name = "server_hash"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2828bf8ef9aaab15f2420a1aa226ded3c367a469c6dec70f7d1be10f4fd9c1c"
original_class_hash = "0x2828bf8ef9aaab15f2420a1aa226ded3c367a469c6dec70f7d1be10f4fd9c1c"
abi = "abis/deployments/models/memory_models_player_player.json"
name = "memory::models::player::player"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "address"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "score"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6b425b791a55c6ea9c5f3761c09b2bca7517e9a0e23c1c6d0187b08b7221214"
original_class_hash = "0x6b425b791a55c6ea9c5f3761c09b2bca7517e9a0e23c1c6d0187b08b7221214"
abi = "abis/deployments/models/memory_models_tile_tile.json"
name = "memory::models::tile::tile"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "position"
type = "Vec2"
key = true

[[models.members]]
name = "tile_id"
type = "u32"
key = false

[[models.members]]
name = "revealed"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x58a1e70bfbacb83aa38595cdcb1b8bb3d35d8acff870d40f148370e857b5aaa"
original_class_hash = "0x58a1e70bfbacb83aa38595cdcb1b8bb3d35d8acff870d40f148370e857b5aaa"
abi = "abis/deployments/models/memory_systems_actions_actions_matched.json"
name = "memory::systems::actions::actions::matched"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "pos1"
type = "Vec2"
key = false

[[models.members]]
name = "pos2"
type = "Vec2"
key = false
