kind = "DojoModel"
class_hash = "0x6b425b791a55c6ea9c5f3761c09b2bca7517e9a0e23c1c6d0187b08b7221214"
original_class_hash = "0x6b425b791a55c6ea9c5f3761c09b2bca7517e9a0e23c1c6d0187b08b7221214"
abi = "manifests/dev/abis/base/models/memory_models_tile_tile.json"
name = "memory::models::tile::tile"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "position"
type = "Vec2"
key = true

[[members]]
name = "tile_id"
type = "u32"
key = false

[[members]]
name = "revealed"
type = "bool"
key = false
