kind = "DojoModel"
class_hash = "0x2828bf8ef9aaab15f2420a1aa226ded3c367a469c6dec70f7d1be10f4fd9c1c"
original_class_hash = "0x2828bf8ef9aaab15f2420a1aa226ded3c367a469c6dec70f7d1be10f4fd9c1c"
abi = "manifests/dev/abis/base/models/memory_models_player_player.json"
name = "memory::models::player::player"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "address"
type = "ContractAddress"
key = true

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "score"
type = "u32"
key = false
