kind = "DojoModel"
class_hash = "0x3d194c293e60495207b5e875c2ccf30532e798b3a5aa292386d22116d5f2763"
original_class_hash = "0x3d194c293e60495207b5e875c2ccf30532e798b3a5aa292386d22116d5f2763"
abi = "manifests/dev/abis/base/models/memory_systems_actions_actions_matched.json"
name = "memory::systems::actions::actions::matched"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "address"
type = "ContractAddress"
key = false

[[members]]
name = "pos1"
type = "Vec2"
key = false

[[members]]
name = "pos2"
type = "Vec2"
key = false
